AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fbot-sam

  Sample SAM Template for fbot-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  DbHost:
    Type: String
    Description: host
    Default: localhost
  DbPASSWORD:
    Type: String
    Description: host
    Default: pass
  Database: 
    Type: String
    Description: host
    Default: database
  Port:
    Type: String
    Description: host
    Default: "3306"
  DbUSER:
    Type: String
    Description: host
    Default: admin

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        DB_HOST: !Ref DbHost
        DB_PASSWORD: !Ref DbPASSWORD
        DATABASE: !Ref Database
        DB_PORT: !Ref Port
        DB_USER: !Ref DbUSER



Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: modules/hello_world/app.lambda_handler
      Runtime: python3.8
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: modules/users/main.insert_user_handler
      Runtime: python3.8
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user
            Method: post

  ListUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: modules/users/main.list_user_handler
      Runtime: python3.8
      Events:
        ListUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list_user
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FBotApi:
    Description: "API Gateway endpoint URL for Prod stage for Handle Users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  CreateUserFunction:
    Description: "Creates a new User"
    Value: !GetAtt CreateUserFunction.Arn
  CreateUserFunctionIamRole:
    Description: "Implicit IAM Role created for Create User function"
    Value: !GetAtt CreateUserFunctionRole.Arn
  ListUserFunction:
    Description: "Lists User from given ID"
    Value: !GetAtt ListUserFunction.Arn
  ListUserFunctionIamRole:
    Description: "Implicit IAM Role created for List User function"
    Value: !GetAtt ListUserFunctionRole.Arn